# Generated by Django 6.0.6 on 2026-06-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostumerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('age', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('email', models.TextField(max_length=200)),
                ('address', models.TextField()),
            ],
        ),
    ]
