# Generated by Django 6.0.6 on 2026-06-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('age', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('email', models.TextField(max_length=200)),
                ('address', models.TextField()),
                ('password', models.CharField(max_length=8)),
                ('confrim_password', models.CharField(max_length=8)),
            ],
        ),
        migrations.DeleteModel(
            name='CostumerModel',
        ),
    ]
