# Generated by Django 6.0.6 on 2026-06-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_customermodel_delete_costumermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
