# Generated by Django 6.0.6 on 2026-06-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store_app", "0004_productsmodel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customermodel",
            old_name="confrim_password",
            new_name="confirm_password",
        ),
        migrations.AlterField(
            model_name="customermodel",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="customermodel",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
